events/urls.py
from django.conf.urls import patterns, include, url
from events.models import Plugin

# Generates the routes for the Controller.
# Typical use is a regular expression for a URL pattern, and then the
# action to call to process requests for that URL pattern.
urlpatterns = patterns('',
    url(r'^$', 'feed.views.displayFeed', name='displayFeed'),
    url(r'^eventpage(?P<id>\d+)$', 'events.views.viewEvent', name='eventpage'),
    url(r'^create', 'events.views.createEvent', name='create'),
    url(r'^join(?P<id>\d+)$', 'events.views.joinEvent', name='joinEvent'),
    url(r'^leave(?P<id>\d+)$', 'events.views.leaveEvent', name='leaveEvent'),
    url(r'^testimonial(?P<id>\d+)$', 'events.views.addTestimonial', name='testimonial'),
    url(r'^testimonial_photo(?P<id>\d+)$', 'events.views.get_testimonial_photo', name='testimonial_photo'),
    url(r'^upload_plugin', 'events.views.upload_plugin', name='upload_plugin'),
    url(r'^edit(?P<id>\d+)$', 'events.views.edit_event', name='edit'),
    url(r'^event_photo(?P<id>\d+)$', 'events.views.get_event_photo', name='event_photo'),
)

feed/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'displayFeed', 'feed.views.displayFeed', name='displayFeed'),
    url(r'index', 'feed.views.displayFeed', name='index'),
    url(r'query', 'feed.views.search', name='search'),
	url(r'updateFeed', 'feed.views.updateFeed', name='updateFeed'),
	url(r'api', 'feed.views.api', name='apidocs'),
	url(r'currentevents', 'feed.views.my_current_events', name='currentevents')
)

finalproject/urls.py
from django.conf.urls import patterns, include, url
from django.core.files import File
from events.models import create_plugin
import os

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('', 
    url(r'^$', include('authenticate.urls')),
    url(r'^authenticate/', include('authenticate.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^feed/', include('feed.urls')),
)


# Create the default plugin before all others
default = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'media', 'plugins', '1.html')

with open(default) as f:
    create_plugin(name='default', template=File(f), filename='1.html')

events/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.contrib.auth.models import User
from datetime import timedelta
from django.utils import timezone
import os
from django.db import transaction
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import force_unicode

SHORT = 50
LONG = 300

class RenameFilesModel(models.Model):
    """ Citation: https://djangosnippets.org/snippets/1129/ """
    RENAME_FILES = {}
    
    class Meta:
        abstract = True
    
    def save(self, force_insert=False, force_update=False):
        rename_files = getattr(self, 'RENAME_FILES', None)
        if rename_files:
            super(RenameFilesModel, self).save(force_insert, force_update)
            force_insert, force_update = False, True
            
            for field_name, options in rename_files.iteritems():
                field = getattr(self, field_name)
                file_name = force_unicode(field)
                name, ext = os.path.splitext(file_name)
                keep_ext = options.get('keep_ext', True)
                final_dest = options['dest']
                if callable(final_dest):
                    final_name = final_dest(self, file_name)
                else:
                    final_name = os.path.join(final_dest, '%s' % (self.pk,))
                    if keep_ext:
                        final_name += ext
                    setattr(self, 'filename', "%s.html" % self.pk)
                if file_name != final_name:
                    field.storage.delete(final_name)
                    field.storage.save(final_name, field)
                    field.storage.delete(file_name)
                    setattr(self, field_name, final_name)
        
        super(RenameFilesModel, self).save(force_insert, force_update)

class GeoLocUser(models.Model):
    """ Application user. Hosts and attends events. """

    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to="profilepic",blank="True")

class Location(models.Model):
    """ Wraps the Google Maps API location. Stores location of events. """

    longitude = models.DecimalField(decimal_places=5, max_digits=20)
    latitude = models.DecimalField(decimal_places=5, max_digits=20)


class Plugin(RenameFilesModel):
    """ Plugin that uses data from the database to customize the rendering of event pages """
    name = models.CharField(max_length=SHORT)
    template = models.FileField(upload_to='plugins/')
    filename = models.CharField(max_length=LONG)

    RENAME_FILES = {
        'template': {'dest': 'plugins/', 'keep_ext': True}
    }

    def __unicode__(self):
        return self.name

# Citation: http://stackoverflow.com/questions/16041232/django-delete-filefield
# Deletes files associated with invalid plugins when they are deleted
@receiver(post_delete, sender=Plugin)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `Plugin` object is deleted.
    """
    if instance.template:
        if os.path.isfile(instance.template.path):
            os.remove(instance.template.path)

@receiver(models.signals.pre_save, sender=Plugin)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `Plugin` object is changed.
    """
    if not instance.pk:
        return False

    try:
        old_file = (Plugin.objects.get(pk=instance.pk)).template
    except Plugin.DoesNotExist:
        return False

    new_file = instance.template
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

#############################
### Event related classes ###
#############################
class Event(models.Model):
    """ A real-world event. Has a host, attensdees, tags, testimonials, and pictures. """

    name = models.CharField(max_length=SHORT)
    description = models.CharField(max_length=LONG)
    
    # Only one user can host an event
    host = models.ForeignKey(GeoLocUser, related_name='hosted_events')
    guests = models.ManyToManyField(GeoLocUser, related_name='events')
    
    # Duration of the event
    start = models.DateTimeField()
    end = models.DateTimeField()

    # Each event has exactly one location. A location can have many events
    location = models.ForeignKey(Location, related_name='events', blank=True)

    # Photo associated with eventw
    picture = models.ImageField(upload_to="eventpic",blank="True")

    #When an event ends, mark as inactive
    active = models.BooleanField(default=True)
    plugin = models.ForeignKey(Plugin, related_name='events')

    def get_plugin(self):
        return self.plugin

    def set_plugin(self, p):
        self.plugin = p
        self.save()
        return

    #@staticmethod
    def is_active(self):
        """ Return whether this event is currently happening """
        curTime = timezone.now()
        afterStart = (curTime - self.start) > timedelta(seconds=0)
        beforeEnd = (self.end - curTime) > timedelta(seconds=0)
        return (afterStart and beforeEnd)

    def is_upcoming(self):
        curTime = timezone.now()
        beforeEnd = (self.end - curTime) > timedelta(seconds=0)
        return beforeEnd

@transaction.commit_on_success
def create_plugin(name, template, filename):
    """ Doesn't allow users to overwrite plugins that have the same name """
    try:
        p = Plugin.objects.get(name__exact=name)
    except:
        p = Plugin(name=name, template=template, filename=filename)
        p.save()
    finally:
        return p

class Tag(models.Model):
    """ Tag is an identifier of an event. Can search to find similar events """

    text = models.CharField(max_length=SHORT)
    events = models.ManyToManyField(Event, related_name='tags')

class Testimonial(models.Model):
    """ Testimonial is text about an event posted by a user """
    
    text = models.CharField(max_length=LONG)
    user = models.ForeignKey(GeoLocUser, related_name='testimonials')
    event = models.ForeignKey(Event, related_name='testimonials')
    image = models.ImageField(upload_to='eventpics/', blank=True)

events/forms.py
from django import forms
from events.models import Event, LONG

class TestimonialForm(forms.Form):
	text = forms.CharField(max_length=LONG, widget=forms.TextInput(attrs={'placeholder': 'Text'}))
	image = forms.FileField(required=False)

class PluginForm(forms.Form):
	name = forms.CharField(max_length=LONG, widget=forms.TextInput(attrs={'placeholder': 'Plugin Name'}))
	template = forms.FileField()

class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Event
        exclude = ()
        widgets = {'picture' : forms.FileInput()}
        fields = ('name', 'description', 'plugin', 'picture')

events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from events.models import *
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from forms import TestimonialForm, PluginForm, EventForm
from mimetypes import guess_type
import json
from django.db import transaction
from datetime import *
from django.core.urlresolvers import reverse
import os
from django.http import Http404

EVENT_REQUIRED_FIELDS = ['name', 'start', 'end']
DEFAULT_PLUGIN = Plugin.objects.get(id=1)

@transaction.commit_on_success
@login_required
def createEvent(request):
	context = {}
	context['user'] = request.user
	context['plugins'] = Plugin.objects.all()
	context['errors'] = []
	if(request.is_ajax() and request.method=="POST"):
		loc = Location(longitude=request.POST['lng'], latitude=request.POST['lat'])
		loc.save()
		plugin = Plugin.objects.get(name__exact=request.POST['plugin'])
		correct_start = request.POST['start'].replace('T', ' ')
		correct_end = request.POST['end'].replace('T', ' ')
		event = Event(host=context['user'].geolocuser, location=loc, name=request.POST['name'], description=request.POST['description'], start=correct_start, end=correct_end, plugin=plugin)
		event.save()
		event.guests.add(request.user.geolocuser)
		for tag in request.POST['tags'].split():
			try:
				t = Tag.objects.get(text__exact=tag)
			except ObjectDoesNotExist:
				t = Tag(text=tag)
				t.save()
			t.events.add(event)
			t.save()
		event.save()
		request_data = {'redirect' : settings.LOGIN_REDIRECT_URL}
		return HttpResponse(json.dumps(request_data), content_type='application/json')
	return render(request, 'events/create.html', context)

@transaction.commit_on_success
def get_event_photo(request, id):
    event = get_object_or_404(Event, id=id)
    if not event.picture:
        raise Http404

    content_type = guess_type(event.picture.name)
    return HttpResponse(event.picture, mimetype=content_type)

@transaction.commit_on_success
@login_required
def joinEvent(request, id):
	context = {}
	context['user'] = request.user
	event = get_object_or_404(Event, id=id)
	event.guests.add(request.user.geolocuser)
	event.save()

	return redirect(request.META.get('HTTP_REFERER', settings.LOGIN_REDIRECT_URL))

@transaction.commit_on_success
@login_required
def leaveEvent(request, id):
	context = {}
	context['user'] = request.user
	event = get_object_or_404(Event, id=id)
	event.guests.remove(request.user.geolocuser)
	event.save()

	return redirect(request.META.get('HTTP_REFERER', settings.LOGIN_REDIRECT_URL))

@transaction.commit_on_success
@login_required
def viewEvent(request, id):
	context = {}
	context['user'] = request.user
	context['event'] = get_object_or_404(Event, id=id)
	context['event_is_active'] = context['event'].is_active()
	""" If leave is true, then the user will have the option to leave the event """
	context['leave'] = context['event'].guests.filter(user=request.user.geolocuser).exists()
	return render(request, context['event'].get_plugin().filename, context)

#Post a testimonial to an event of the id
@transaction.commit_on_success
@login_required
def addTestimonial(request, id):
	context = {}
	context['user'] = request.user
	context['event'] = get_object_or_404(Event, id=id)
	if request.method == "GET":
		return redirect(request.META['HTTP_REFERER'])
	else:
		form = TestimonialForm(request.POST, request.FILES)
		if form.is_valid():
			text = form.cleaned_data['text']
			image = form.cleaned_data['image']
			testimonial = Testimonial(text=text, image=image, user=request.user.geolocuser, event=context['event'])
			testimonial.save()
		return redirect(request.META['HTTP_REFERER'])


@transaction.commit_on_success
def get_testimonial_photo(request, id):
	testimonial = Testimonial.objects.get(id=id)

	if not testimonial.image:
		raise Http404

	content_type = guess_type(testimonial.image.name)
	return HttpResponse(testimonial.image, mimetype=content_type)

@transaction.commit_on_success
@login_required
def upload_plugin(request):
	context = {}
	context['user'] = request.user
	if request.method == "POST":
		form = PluginForm(request.POST, request.FILES)
		if form.is_valid():
			name = form.cleaned_data.get('name')
			template = form.cleaned_data.get('template')
			filename = template._name
			p = create_plugin(name=name, template=template, filename=filename)
			p.save()
			context['event'] = get_object_or_404(Event, id=1)
			try:
				validate_plugin(p)
				context['event'].set_plugin(p)
				context['dummy'] = True
				return render(request, p.filename, context)
			except Exception as e:
				context['error'] = e
				p.delete()
				context['event'].set_plugin(DEFAULT_PLUGIN)
				return render(request, 'feed/bad_plugin.html', context)
	return redirect(settings.LOGIN_REDIRECT_URL)

@transaction.commit_on_success
def validate_plugin(p):
	p.template.open('rb')
	template_text = p.template.read().split('\n')
	p.template.close()
	firstLine = template_text[0]
	stripped = "".join(firstLine.split())
	if stripped != "{%extends'events/base_event.html'%}":
		raise Exception("First line of file must be: {%% extends 'events/base_event.html' %%}. \
						\n It is currently %s" % firstLine)

	for i, line in enumerate(template_text):
		splitLine = "".join(line.split())
		if '<form' in splitLine:
			raise Exception("Line %d contains a form. Forms are not allowed in templates.\n Line: %s." \
								% (i, line))
		if '<script' in splitLine:
			raise Exception("Line %d contains a script. Forms are not allowed in templates. \nLine: %s." \
								% (i, line))
	return

@transaction.commit_on_success
@login_required
def edit_event(request, id):
	context = {}
	context['user'] = request.user
	context['event'] = get_object_or_404(Event, id=id)
	# Only the host of the event can edit (prevents url hacking)
	if context['user'].geolocuser != context['event'].host:
		raise Http404

	if request.method=="GET":
		context['form'] = EventForm(instance=context['event'])
		return render(request,'events/edit.html', context)

	form = EventForm(request.POST, request.FILES, instance=context['event'])
	if not form.is_valid():
		context['form'] = form
		return redirect(reverse('edit', args=[id]))
	form.save()
	return redirect(reverse('eventpage', args=[id]))

events/templates/events/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

    <title>EventFinder</title>

    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/fancySelect.css" rel="stylesheet">
    <style>
      #footer {
    position:absolute;
    bottom:0;
    width:100%;
    height:25px;      /* Height of the footer */
  }
  </style>
    {% block css %}
    {% endblock %}

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>

    <script src="/static/js/jquery-1.8.3.min.js" type="text/javascript"></script>
    <script src="/static/js/json2.js" type="text/javascript"></script>
    <script src="/static/js/app.js" type="text/javascript"></script>
    <script src="/static/js/map.js" type="text/javascript"></script>
    <script src="/static/js/fancySelect.js" type="text/javascript"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
  </head>
  <body>

<div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <a class="brand" href="/feed/index.html">EventFinder</a>
      <ul class="nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {{user.first_name}}
            <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
              <li><a href="/authenticate/change_password">Change Password</a></li>
              <li><a href="/authenticate/logout">Logout</a></li>
            </ul>
          </li>
          <li>
              <a href="{% url 'create' %}"> Create Event</a>
          </li>
          <li>
              <a href="{% url 'currentevents' %}"> My Events </a>
          </li>
          <li>
              <a href="{% url 'apidocs' %}"> API Documentation </a>
          </li>
          <li>
          <li>
              <form class="navbar-search" action="{% url 'search' %}" method="post">
                <i class="icon-white icon-search"></i>
                <input type="text" class="search-query" name="query">
              </input>
                {% csrf_token %}
              </form>
            </li>
              </ul>
            </div>
          </div>

    <div id="content" class="container">
      {% block content %}

      {% endblock %}
    </div>
    <footer id="footer">
\    </footer>
  </body>
</html>

events/templates/events/base_event.html
{% extends 'events/base.html' %}
{% block css %}
{% endblock css %}
{% block content %}

{% if dummy %}
{% else %}
{% if user.geolocuser == event.host %}
<a href="{% url 'edit' event.id %}"><p > Edit Event <p></a>
{% else %}
    {% if leave %}
    <a href="{% url 'leaveEvent' event.id %}"><p> Leave Event <p></a>
    {% else %}
    <a href="{% url 'joinEvent' event.id %}"><p> Join Event <p></a>
    {% endif %}
{% endif %}
{% endif %}

{% block event_content %}
{% endblock %}
{% if leave and event_is_active and not dummy %}
    <form class="testimonial-form" action="{% url 'testimonial' event.id %}" enctype='multipart/form-data' method="post">
      <p>Write a testimonial:</p> <input type="textarea" name="text">
       <br/>
      <input type="file" name="image">
      <br/>
      <button type="submit" class="btn btn-primary">Submit</button>
      {% csrf_token %}
    </form>
{% endif %}
{% endblock %}

events/templates/events/create.html
{% extends 'events/base.html' %}
{% block css %}
<style>
label {color: white;}
</style>
   <link href="/static/css/custom.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container">
        <h1> Create an event </h1>
    <div class="row-fluid">
<div class="span6">
    <form enctype='multipart/form-data' class ="createForm" method="post">{% csrf_token %}
    	<tr><th><label for="id_name">Name:</label></th><td><input id="id_name" maxlength="50" name="name" type="text" /></td></tr>
        <tr><th><label for="id_description">Description:</label></th><td><input id="id_description" maxlength="300" size="300" name="description" type="text"/></td></tr>
        <tr><th><label for="id_tags">Tags:</label></th><td><input id="id_tags" maxlength="300" placeholder="Space separated tags" name="tags" type="text" /></td></tr>
        <tr><th><label for="id_start">Start:</label></th><td><input id="id_start" name="start" type="datetime-local" /></td></tr>
        <tr><th><label for="id_end">End:</label></th><td><input id="id_end" name="end" type="datetime-local"/></td></tr>
        <tr><th><label for="id_plugin">Plugin:</label></th><td><select id="plugin" name="plugin">
        {% for plugin in plugins %}
            <option value="{{plugin.name}}">{{plugin.name}}</option>
        {% endfor %}
    </select>
        </td></tr>
    <br>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% for error in errors %}
<p style="color: red"> {{error}} </p>
{% endfor %}
</div>
<div class="span6">
    <div class="mapform">
        <div >
          <input id="target" type="text" placeholder="Find a location for your event">
        </div>
        <div id="map-canvas"></div>
    </div>
</div>
    </div>
  </div>
{% endblock content %}

events/templates/events/edit.html
{% extends "events/base.html" %}
{% block css %}
{% endblock %}
{% block content %}
    <div>
        {% if form.picture.value %}
        <img src="{% url 'event_photo' event.id %}" alt="{{event.host.geolocuser.name}}" class="text" width="104" height="104">
        {% endif %}
      </div>
    <form enctype='multipart/form-data' action="{% url 'edit' event.id %}" method="post">{% csrf_token %}
      {{form}}
    <br>
    {% for error in form.errors %}
    <p>{{error}}</p>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}